config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'
  get 'public_recipes', to: 'home#public_recipes'
  get 'shopping_list', to: 'home#shopping_list'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :foods, except: :update

  resources :recipes, except: :update do
    resources :recipe_foods, only: %i[create destroy edit new update]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @recipes = Recipe.includes([:user]).where(user: current_user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.includes([:food]).includes([:recipe]).where(recipe_id: params[:id])
  end

  def destroy
    @recipes = Recipe.find(params[:id])

    @recipes.destroy
    redirect_to recipes_path
  end

  def create
    if @recipe.save
      flash[:notice] = 'Recipe saved successfully'
    else
      flash[:alert] = 'Recipe not saved'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cooking_time, :preparation_time, :public)
      .merge({ user_id: current_user.id })
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe.html.erb
<div class="float-none card mt-3">
  <div class="card-body">
    <h3 class="card-title text-primary"><%= recipe.name %>
      <% if recipe.public? %>
        <span class="h5 text-secondary">by
          <%= recipe.user.name %></span>
      <% end %>
    </h3>
    <p class="card-text"><%= recipe.description %></p>
    <%= link_to 'See Details', recipe_path(recipe.id), 
        class: 'btn btn-primary' %>
    <% if can? :destroy, recipe %>
      <%= link_to 'Remove', recipe_path(recipe.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure"},
        class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/recipes/_thead.html.erb
<thead class="thead-dark">
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Actions</th>
  </tr>
</thead>

app/views/recipes/index.html.erb
<section>
  <h1 class="mt-2 text-center">Recipes</h1>
  <hr>
  <%= link_to 'Create new recipe', new_recipe_path, 
  class: 'btn btn-primary float-end mb-4' %>
  <div class="container mt-5" style="clear:both;">
    <%= render @recipes %>
    <p>&nbsp;</p>
  </div>
</section>

app/views/recipes/new.html.erb
<section>
  <h1 class="mt-2 text-center">New Recipe</h1>
  <hr>
  <%= form_with url: "/recipes", method: :post, scope: :recipe, class: 'form-body' do |form| %>
    <div class="form-group">
      <%= form.label :Name %>
      <br>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :Preparation_time %>
      <br>
      <%= form.text_field :preparation_time, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :Cooking_time %>
      <br>
      <%= form.text_field :cooking_time, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :Description %>
      <br>
      <%= form.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-check">
      <%= form.label(:public, class: 'form-check-label') %>
      <%= form.check_box(:public, class: 'form-check-input') %>
    </div>

    <div class="actions"><%= form.submit class: 'btn btn-primary' %></div>
  <% end %>
</section>

app/views/recipes/show.html.erb
<h1 class="mt-2 text-center"><%= @recipe.name %></h1>
<hr>
<div class="container mt-5" style="clear:both;">
  <div class='d-flex info-recipe justify-content-between '>
    <div class=''>
      <p class='mb-3 fs-5 fw-bold'>
        Preparation time: 
        <span class="fw-normal"><%=@recipe.preparation_time%></span> 
      </p>
      <p class='mb-3 fs-5 fw-bold'>
        Cooking time: 
        <span class="fw-normal"><%=@recipe.cooking_time%></span> 
      </p>
    </div>
    <div class=''>
      <h3>Public<h3>
      <label class="switch">
        <input type="checkbox" <% if @recipe.public %>checked<% end %> disabled>
        <span class="slider round"></span>
      </label>
    </div>
  </div>
  <p class='mb-3 fs-5'><%= @recipe.description %></p>
  <div class='d-flex info-recipe justify-content-between '>
    <%=link_to 'Generate shopping list', shopping_list_path, class: 'btn btn-primary' %>
    <% if can? :create, @recipe %>
      &nbsp;&nbsp;<%= link_to 'Add new ingredient', new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-primary' %>
    <% end %>
  </div>
  <p>&nbsp;</p>

  <% unless @recipe_foods.empty? %>
    <table class="table">
      <%= render 'thead' %>
      <tbody>
        <%= render @recipe_foods %>
      </tbody>
    </table>
    <p>&nbsp;</p>
  <% else %>
    <%= render html: '<p /><h1>You have no Foods in the recipe</h1>'.html_safe %>
  <% end %>
</div>