config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'
  get 'public_recipes', to: 'home#public_recipes'
  get 'shopping_list', to: 'home#shopping_list'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :foods, except: :update

  resources :recipes, except: :update do
    resources :recipe_foods, only: %i[create destroy edit new update]
  end
end

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |name, msg| -%>
    <% if name=='alert' %>
      <div
        class='alert alert-danger flash'
        data-controller="removals"
        data-action="animationend->removals#remove"
      >
        <%= msg %>
      </div>
    <% else %>
      <div
        class='alert alert-info flash'
        data-controller="removals"
        data-action="animationend->removals#remove"
      >
        <%= msg %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_nav-menu.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to image_tag('https://cdn-icons-png.flaticon.com/512/1397/1397128.png', size: '55'), root_path, class: 'nav-brand' %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Shopping List', shopping_list_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Public Recipes', public_recipes_path, class: 'nav-link' %>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to 'Log out', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link' %>
          <% else %>
            <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_publicRecipe.html.erb
<%= turbo_frame_tag "toggle-public", class: 'switch-container' do %>
  <%= form_with(model: @recipe) do |form| %>
    <%= form.label "Public" %>
    <label class="switch">
      <%= form.submit "Public", class: @recipe.public ? "public" : "" %>
      <span class="slider"/>
    </label>
  <% end %>
<% end %>