config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'
  get 'public_recipes', to: 'home#public_recipes'
  get 'shopping_list', to: 'home#shopping_list'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :foods, except: :update

  resources :recipes, except: :update do
    resources :recipe_foods, only: %i[create destroy edit new update]
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def create
    if @food.save
      flash[:notice] = 'Food saved successfully'
    else
      flash[:alert] = 'Food not saved'
    end
    redirect_to foods_path
  end

  def destroy
    @food.destroy
    flash.now[:notice] = 'Food was deleted!'
    redirect_to foods_path
  rescue ActiveRecord::InvalidForeignKey
    flash.now[:alert] = 'Food cannot be deleted!'
    redirect_to foods_path
  end

  def index
    @foods = Food.where(user: current_user)
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
      .merge({ user_id: current_user.id })
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td><%= food.price %></td>
  <td><%= food.quantity %></td>
  <td>
    <% unless food.recipe_foods.exists? %>
      <%= link_to 'Delete', food_path(food), 
        data: { turbo_confirm: "Are you sure?", turbo_method: :delete },
        class: 'btn btn-sm btn-danger' %>
    <% end %>
  </td>
</tr>

app/views/foods/_thead.html.erb
<thead class="thead-dark">
  <tr>
    <th>Food</th>
    <th>Measurement Unit</th>
    <th>Unit Price</th>
    <th>Quantity</th>
    <th>Actions</th>
  </tr>
</thead>

app/views/foods/index.html.erb
<section>
  <h1 class="mt-2 text-center">Food list</h1>
  <hr/>

  <%= link_to 'Add Food', new_food_path, class: 'btn float-end btn-primary mt-1 mb-4' %>
  <div class="container mt-5" style="clear:both;">
    <% unless @foods.empty? %>
      <table class="table">
        <%= render 'thead' %>
        <tbody>
          <%= render @foods %>
        </tbody>
      </table>
    <% else %>
      <%= render html: '<p /><h1>You have no Foods in the database</h1>'.html_safe %>
    <% end %>
  </div>
</section>

app/views/foods/new.html.erb
<section>
  <h1 class="mt-2 text-center">New Food</h1>
  <hr/>
  <div class="container mt-5" style="clear:both;">
    <%= form_with model: @food, url: foods_path, scope: :food do |form| %>
      <div class="form-group">
        <%= form.label :Name %>
        <br>
        <%= form.text_field :name, placeholder: :Name, required: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Measurement_Unit %>
        <br>
        <%= form.text_field :measurement_unit, placeholder: :Measurement_Unit, required: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Unit_Price %>
        <br>
        <%= form.number_field :price, step: 1, placeholder: :Unit_Price, required: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Quantity %>
        <br>
        <%= form.number_field :quantity, step: 1, placeholder: "Quantity", required: true, class: 'form-control' %>
      </div>
      <div class="actions"><%= form.submit class: 'btn btn-primary' %></div>
    <% end %>
  </div>
</section>