config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'
  get 'public_recipes', to: 'home#public_recipes'
  get 'shopping_list', to: 'home#shopping_list'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :foods, except: :update

  resources :recipes, except: :update do
    resources :recipe_foods, only: %i[create destroy edit new update]
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe_food, only: %i[show edit update destroy]
  load_and_authorize_resource

  def create
    if @recipe_food.save
      flash[:notice] = 'RecipeFood saved successfully'
    else
      flash[:alert] = 'RecipeFood not saved'
    end
    redirect_to recipe_path(params[:recipe_id])
  end

  def destroy
    @recipe_food.recipe_id = nil
    @recipe_food.food_id = nil
    @recipe_food.destroy

    redirect_to request.path
  end

  def new
    @foods = Food.where(user: current_user)
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food.quantity = recipe_food_params[:quantity]
    @recipe_food.save
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.where(recipe_id: params[:recipe_id], food_id: params[:id]).first
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity).merge(params.slice(:recipe_id).permit(:recipe_id))
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_recipe_food.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.quantity %></td>
  <td><%= recipe_food.food.price %></td>
  <td>
    <% if can? :update, recipe_food.recipe %>
      <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food),
        class: 'btn btn-sm btn-primary' %>
    <% end %>
    <% if can? :destroy, recipe_food.recipe %>
      <%= link_to 'Remove', recipe_recipe_food_path(recipe_food.recipe_id, recipe_food.food_id), 
        data: { turbo_method: :delete },
        class: 'btn btn-sm btn-danger' %>
    <% end %>
  </td>
</tr>

app/views/recipe_foods/edit.html.erb
<h2>Edit quantity of: <%= @recipe_food.food.name %>

<%= form_with model: @recipe_food, url: recipe_recipe_food_path, method: :patch do |form| %>
  <%= form.label :quantity %>
  <%= form.number_field :quantity %>
  <%= form.submit "Update" %>
<% end %>

app/views/recipe_foods/new.html.erb
<section>
  <h1 class="mt-2 text-center">Add Food to Recipe</h1>
  <hr>
  <div class="container mt-5" style="clear:both;">
    <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(params[:recipe_id]), scope: :recipe_food do |form| %>
      <div class="form-group">
        <%= form.label :Food %>
        <br/>
        <%= form.select :food_id, @foods.map { |t| [t.name, t.id]}, {}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :Quantity %>
        <br/>
        <%= form.number_field :quantity, step: 1, placeholder: "Quantity", required: true, class: 'form-control' %>
      </div>
      <div class="actions"><%= form.submit class: 'btn btn-primary' %></div>
    <% end %>
  </div>
</section>

app/views/recipe_foods/update.html.erb
<h1>RecipeFoods#update</h1>
<p>Find me in app/views/recipe_foods/update.html.erb</p>